/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 components/models/h3xHouse.glb -o components/h3xHouse.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function h3xHouse(props: any) {
  const { nodes, materials } = useGLTF('/../public/models/h3xHouse.glb')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/../public/models/h3xHouse.glb')
